### ISSUE TITLE
How to get the event data

### ISSUE THREAD

**Issue by robust1997** [kev-in-ta/l2e#1]
Hi Kevin, thanks for this great work. It simplifies the calibration work between lidar and dvs. I read this paper from ICRA several times, but one thing I still don't understand.
My question is: How to generate events from the environment without moving the event camera? From my understanding, the answer from the paper is that events are triggered by the laser from the lidar. However, when I use the same event camera and a 64 channels lidar in an almost dark room, few events appear. 
Do I understand your method correctly? Or this is caused by the room is not dark enough. 
Thanks for this great work and help:)

**Comment by kev-in-ta** [comment]
Hi! 
In our setting we found that the default settings for the Prophesee cameras worked quite well for detecting lidar pulses as events. You can also adjust the biases / thresholds for detections using `metavision_player`. You are correct that you should avoid rooms that are exposed to sunlight (we performed these in a garage setting).
See [documentation on changing biases](https://docs.prophesee.ai/stable/metavision_player/biases.html)
See [bias explanations](https://docs.prophesee.ai/stable/hw/manuals/biases.html#chapter-biases)

We also used quite a dense MEMS-based lidar. We could see the lidar scan as it traversed through the scene, but a sparser lidar may be more difficult to recognise. Have you tried accumulating the events to see if there are clear patterns matching your lidar?

**Comment by robust1997** [comment]
> Hi! In our setting we found that the default settings for the Prophesee cameras worked quite well for detecting lidar pulses as events. You can also adjust the biases / thresholds for detections using `metavision_player`. You are correct that you should avoid rooms that are exposed to sunlight (we performed these in a garage setting). See [documentation on changing biases](https://docs.prophesee.ai/stable/metavision_player/biases.html) See [bias explanations](https://docs.prophesee.ai/stable/hw/manuals/biases.html#chapter-biases)
> 
> We also used quite a dense MEMS-based lidar. We could see the lidar scan as it traversed through the scene, but a sparser lidar may be more difficult to recognise. Have you tried accumulating the events to see if there are clear patterns matching your lidar?

Hi Kevin, I think the problem is caused by the environment is not dark enough. Today I find a dark room and the dvs shows the event caused by lidar scan. 

Thanks again for your help:)
