### ISSUE TITLE
How to get the config.json  parameter

### ISSUE THREAD

**Issue by yanggit1116** [kev-in-ta/l2e#2]
"x"   "y"  "z"   "rz" "ry"    "rx"   "Rodrigues"

**Comment by kev-in-ta** [comment]
Hi! If you're asking about the config for the sample data, that's provided in the example config.
If you're looking for how to describe these parameters for your own custom set-up, you'll have to find rough initialisations based on your hardware set-up. The parameters are specified as the lidar pose in the camera frame (i.e. the transform that would bring the lidar into the camera coordinate system).
