### ISSUE TITLE
Hello, I saw that the sample data you provided contains RGB images. Can you share the bag of Laser M1 lidar and RGB images, including camera internal parameters?

### ISSUE THREAD

**Issue by af-doom** [kev-in-ta/l2e#3]
My research is on the calibration of cameras and lasers. I need test data. Your data set meets my needs very well. I am very grateful.

**Comment by kev-in-ta** [comment]
Hi! Thank you for the interest! I'll try to get back to you this weekend to see if I still have the data, I'm currently away from my main working site. I know I have the single example here of a rosbag:
https://drive.google.com/file/d/1yOeh6oB30gYrakfRZU4Pxx3r9lyid7Uh/view?usp=sharing

**Comment by af-doom** [comment]
> Hi! Thank you for the interest! I'll try to get back to you this weekend to see if I still have the data, I'm currently away from my main working site. I know I have the single example here of a rosbag: https://drive.google.com/file/d/1yOeh6oB30gYrakfRZU4Pxx3r9lyid7Uh/view?usp=sharing

Thank you very much for your reply. I have already downloaded this package. But I need multiple packages containing RGB images and laser point clouds, as well as the intrinsic parameters of the RGB camera. It's too much trouble for you, thank you.

**Comment by af-doom** [comment]
> Hi! Thank you for the interest! I'll try to get back to you this weekend to see if I still have the data, I'm currently away from my main working site. I know I have the single example here of a rosbag: https://drive.google.com/file/d/1yOeh6oB30gYrakfRZU4Pxx3r9lyid7Uh/view?usp=sharing

Sorry for your trouble, please let me know if you can't share the data. I'll look for other solutions. thank you so much

**Comment by kev-in-ta** [comment]
Hi! Here's a link to  collection bags with lidar and rgb data. You'll have to add in the intrinsic calibration yourself (see the configs in the repo!)

https://drive.google.com/file/d/1MwmEaagSr4eUPal2Ltl4jvskPO5LzKRf/view?usp=sharing

**Comment by af-doom** [comment]
> Hi! Here's a link to collection bags with lidar and rgb data. You'll have to add in the intrinsic calibration yourself (see the configs in the repo!)
> 
> https://drive.google.com/file/d/1MwmEaagSr4eUPal2Ltl4jvskPO5LzKRf/view?usp=sharing

Wow, thank you so much. Are the internal parameters in the repository for RGB cameras? In addition, do you know the approximate reference values for the external parameters between the RGB camera and the laser, because what you are doing is related to event cameras.

**Comment by af-doom** [comment]
> Hi! Here's a link to collection bags with lidar and rgb data. You'll have to add in the intrinsic calibration yourself (see the configs in the repo!)
> 
> https://drive.google.com/file/d/1MwmEaagSr4eUPal2Ltl4jvskPO5LzKRf/view?usp=sharing

{
  "cam": {
    "K": [
      [1043.9777149158745, 0, 620.3542209837874],
      [0, 1044.3901630718665, 343.75690903851563],
      [0, 0, 1]
    ],
    "D": [
      -0.4558224833720169, 0.29944271675699663, 6.867280678643097e-5,
      -0.00012528851559686296, -0.139114502340535
    ],
    "x": 0.188,
    "y": 0,
    "z": -0.05,
    "rz": 90,
    "ry": -90,
    "rx": 0,
    "Rodrigues": [1.20919958, -1.20919958, 1.20919958]
  }
}
Are the parameters in config.json RGB camera or event camera internal parameters?
