### ISSUE TITLE
Hello, I have another question. That is, the configuration file only provides one internal parameter, whether it is an event camera or an RGB camera.

### ISSUE THREAD

**Issue by af-doom** [kev-in-ta/l2e#4]
Thank you very much. Sorry to trouble you.

**Comment by kev-in-ta** [comment]
Ah sorry, you are correct. Below should be the intrinsic parameters for the RGB camera images. 
```
    "rgb": {
        "K": [
            [
                1215.16206202384,
                0,
                931.46704145638
            ],
            [
                0,
                1215.5773507687247,
                541.5467734550551
            ],
            [
                0,
                0,
                1
            ]
        ],
        "x": 0.106,
        "y": 0,
        "z": -0.05,
        "rz": 90,
        "ry": -90,
        "rx": 0,
        "Rodrigues": [
            1.20919958,
            -1.20919958,
            1.20919958
        ]
```

**Comment by af-doom** [comment]
> Ah sorry, you are correct. Below should be the intrinsic parameters for the RGB camera images.
> 
> ```
>     "rgb": {
>         "K": [
>             [
>                 1215.16206202384,
>                 0,
>                 931.46704145638
>             ],
>             [
>                 0,
>                 1215.5773507687247,
>                 541.5467734550551
>             ],
>             [
>                 0,
>                 0,
>                 1
>             ]
>         ],
>         "x": 0.106,
>         "y": 0,
>         "z": -0.05,
>         "rz": 90,
>         "ry": -90,
>         "rx": 0,
>         "Rodrigues": [
>             1.20919958,
>             -1.20919958,
>             1.20919958
>         ]
> ```

Wow, thank you so much.You're really kind. Sorry to bother you.
