### ISSUE TITLE
Sorry, I was so excited just now, and now I find that the internal parameters you just provided have no distortion coefficient. Is this normal?

### ISSUE THREAD

**Issue by af-doom** [kev-in-ta/l2e#5]
"x": 0.106,
        "y": 0,
        "z": -0.05,
        "rz": 90,
        "ry": -90,
        "rx": 0,
        "Rodrigues": [
            1.20919958,
            -1.20919958,
            1.20919958
In addition, the meaning of these parameters is

**Comment by kev-in-ta** [comment]
I am apparently pretty bad at copy-and-pasting. Here are the distortion parameters as well.
```
    "cam1": {
        "K": [
            [
                1215.16206202384,
                0,
                931.46704145638
            ],
            [
                0,
                1215.5773507687247,
                541.5467734550551
            ],
            [
                0,
                0,
                1
            ]
        ],
        "D": [
            -0.36565734884394796,
            0.19454341750019136,
            -0.0003778025271473721,
            9.299129873097343e-05,
            -0.0637399451159775
        ],
        "x": 0.106,
        "y": 0,
        "z": -0.05,
        "rz": 90,
        "ry": -90,
        "rx": 0,
        "Rodrigues": [
            1.20919958,
            -1.20919958,
            1.20919958
        ]
    },
```

**Comment by af-doom** [comment]
Thank you so much. Also, is there a rough reference value for the external parameters between lidar and cameras



---Original---
From: "Kevin ***@***.***&gt;
Date: Mon, Apr 29, 2024 22:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kev-in-ta/l2e] Sorry, I was so excited just now, and now I findthat the internal parameters you just provided have no distortion coefficient.Is this normal? (Issue #5)




 
I am apparently pretty bad at copy-and-pasting. Here are the distortion parameters as well.
     "cam1": {         "K": [             [                 1215.16206202384,                 0,                 931.46704145638             ],             [                 0,                 1215.5773507687247,                 541.5467734550551             ],             [                 0,                 0,                 1             ]         ],         "D": [             -0.36565734884394796,             0.19454341750019136,             -0.0003778025271473721,             9.299129873097343e-05,             -0.0637399451159775         ],         "x": 0.106,         "y": 0,         "z": -0.05,         "rz": 90,         "ry": -90,         "rx": 0,         "Rodrigues": [             1.20919958,             -1.20919958,             1.20919958         ]     },

**Comment by kev-in-ta** [comment]
The xyz and [rotvec](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_rotvec.html) parameters should give the lidar relative to the camera frame.
